spring.application.name=minimarket-plus
server.port=8080
spring.datasource.url=jdbc:h2:mem:minimarket;DB_CLOSE_DELAY=-1;MODE=PostgreSQL
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.open-in-view=false
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
app.jwt.secret=MiniMarketPlusClaveJwtSegura2026ConMasDeTreintaYDosCaracteres
app.jwt.expiration-ms=3600000
